[build]
  publish = "dist"
  command = "npm run build"

[dev]
  publish = "./dist"
  command = "npm run watch"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# [[redirects]]
#   from = "/cart"
#   to = "/.netlify/functions/cart-view"
#   status = 200


[context.production]
  environment = { SHOPIFY_API_ENDPOINT = "https://saalt-dev.myshopify.com/api/2022-01/graphql.json", SHOPIFY_STOREFRONT_API_TOKEN = "6541f64710db1763510c55905fd1aaba" }

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "valitics:staging"